#!/bin/bash

#$ -cwd # execute the job from the current directory

#$ -S /bin/bash #set bash environment

#$ -N SlideClass # name of the job as it will appear in qstat -f

#$ -o /share/data40T_v2/twalter/PBS/OUT

#$ -e /share/data40T_v2/twalter/PBS/ERR

#$ -l h_vmem=4G

## others optional options

## #$ -V  Pass all current environment variables to the job.

## #$ -q bath # Tell the system which queue to use

### #$ -t 1-160 # les valeures successives que va prendre $SGE_TASK_ID

### #$ -tc 160 # nbre de job qui peuvent fonctionner en parallèle ensemble

SOURCE_FOLDER=/cbio/donnees/twalter/src/challengecam/cluster

source /cbio/donnees/twalter/src/challengecam/cluster/bash_files/twalter_code_profile

python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=01
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=02
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=03
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=04
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=05
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=06
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=07
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=08
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=09
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=010
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=011
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=012
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=013
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=014
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=015
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=016
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=017
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=018
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=019
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=020
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=021
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=022
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=023
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=024
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=025
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=026
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=027
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=028
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=029
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=030
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=031
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=032
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=033
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=034
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=035
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=036
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=037
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=038
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=039
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=040
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=041
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=042
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=043
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=044
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=045
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=046
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=047
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=048
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=049
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=050
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=051
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=052
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=053
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=054
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=055
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=056
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=057
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=058
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=059
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=060
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=061
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=062
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=063
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=064
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=065
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=066
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=067
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=068
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=069
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=070
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=071
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=072
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=073
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=074
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=075
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=076
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=077
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=078
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=079
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=080
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=081
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=082
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=083
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=084
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=085
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=086
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=087
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=088
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=089
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=090
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=091
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=092
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=093
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=094
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=095
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=096
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=097
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=098
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=099
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=0100
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=0101
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=0102
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=0103
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=0104
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=0105
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=0106
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=0107
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=0108
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=0109
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=0110
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=0111
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=0112
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=0113
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=0114
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=0115
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=0116
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=0117
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=0118
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=0119
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=0120
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=0121
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=0122
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=0123
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=0124
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=0125
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=0126
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=0127
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=0128
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=0129
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/Pred_data_set/ --output_folder=/share/data40T_v2/challengecam_results/probmap/pred_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=0130
