#!/bin/bash

#$ -cwd # execute the job from the current directory

#$ -S /bin/bash #set bash environment

#$ -N SlideClass # name of the job as it will appear in qstat -f

#$ -o /share/data40T_v2/twalter/PBS/OUT

#$ -e /share/data40T_v2/twalter/PBS/ERR

#$ -l h_vmem=4G

## others optional options

## #$ -V  Pass all current environment variables to the job.

## #$ -q bath # Tell the system which queue to use

### #$ -t 1-160 # les valeures successives que va prendre $SGE_TASK_ID

### #$ -tc 160 # nbre de job qui peuvent fonctionner en parallèle ensemble

SOURCE_FOLDER=/cbio/donnees/twalter/src/challengecam/cluster

source /cbio/donnees/twalter/src/challengecam/cluster/bash_files/twalter_code_profile

python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/results_on_train/ --output_folder=/share/data40T_v2/challengecam_results/probmap/train_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=01
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/results_on_train/ --output_folder=/share/data40T_v2/challengecam_results/probmap/train_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=02
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/results_on_train/ --output_folder=/share/data40T_v2/challengecam_results/probmap/train_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=03
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/results_on_train/ --output_folder=/share/data40T_v2/challengecam_results/probmap/train_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=04
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/results_on_train/ --output_folder=/share/data40T_v2/challengecam_results/probmap/train_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=05
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/results_on_train/ --output_folder=/share/data40T_v2/challengecam_results/probmap/train_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=06
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/results_on_train/ --output_folder=/share/data40T_v2/challengecam_results/probmap/train_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=07
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/results_on_train/ --output_folder=/share/data40T_v2/challengecam_results/probmap/train_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=08
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/results_on_train/ --output_folder=/share/data40T_v2/challengecam_results/probmap/train_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=09
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/results_on_train/ --output_folder=/share/data40T_v2/challengecam_results/probmap/train_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=010
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/results_on_train/ --output_folder=/share/data40T_v2/challengecam_results/probmap/train_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=011
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/results_on_train/ --output_folder=/share/data40T_v2/challengecam_results/probmap/train_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=012
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/results_on_train/ --output_folder=/share/data40T_v2/challengecam_results/probmap/train_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=013
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/results_on_train/ --output_folder=/share/data40T_v2/challengecam_results/probmap/train_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=014
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/results_on_train/ --output_folder=/share/data40T_v2/challengecam_results/probmap/train_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=015
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/results_on_train/ --output_folder=/share/data40T_v2/challengecam_results/probmap/train_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=016
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/results_on_train/ --output_folder=/share/data40T_v2/challengecam_results/probmap/train_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=017
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/results_on_train/ --output_folder=/share/data40T_v2/challengecam_results/probmap/train_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=018
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/results_on_train/ --output_folder=/share/data40T_v2/challengecam_results/probmap/train_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=019
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/results_on_train/ --output_folder=/share/data40T_v2/challengecam_results/probmap/train_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=020
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/results_on_train/ --output_folder=/share/data40T_v2/challengecam_results/probmap/train_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=021
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/results_on_train/ --output_folder=/share/data40T_v2/challengecam_results/probmap/train_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=022
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/results_on_train/ --output_folder=/share/data40T_v2/challengecam_results/probmap/train_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=023
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/results_on_train/ --output_folder=/share/data40T_v2/challengecam_results/probmap/train_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=024
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/results_on_train/ --output_folder=/share/data40T_v2/challengecam_results/probmap/train_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=025
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/results_on_train/ --output_folder=/share/data40T_v2/challengecam_results/probmap/train_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=026
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/results_on_train/ --output_folder=/share/data40T_v2/challengecam_results/probmap/train_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=027
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/results_on_train/ --output_folder=/share/data40T_v2/challengecam_results/probmap/train_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=028
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/results_on_train/ --output_folder=/share/data40T_v2/challengecam_results/probmap/train_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=029
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/results_on_train/ --output_folder=/share/data40T_v2/challengecam_results/probmap/train_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=030
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/results_on_train/ --output_folder=/share/data40T_v2/challengecam_results/probmap/train_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=031
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/results_on_train/ --output_folder=/share/data40T_v2/challengecam_results/probmap/train_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=032
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/results_on_train/ --output_folder=/share/data40T_v2/challengecam_results/probmap/train_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=033
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/results_on_train/ --output_folder=/share/data40T_v2/challengecam_results/probmap/train_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=034
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/results_on_train/ --output_folder=/share/data40T_v2/challengecam_results/probmap/train_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=035
python $SOURCE_FOLDER/image_prediction2.py --classifier_name=/share/data40T_v2/challengecam_results/training/best_classifier.pickle --feature_folder=/share/data40T_v2/challengecam_results/results_on_train/ --output_folder=/share/data40T_v2/challengecam_results/probmap/train_data_set --subsample_factor=16 --sub_sample_folder=YES --slide_number=036
